version: '3.8'

services:
  products_db:
    image: postgres:15-alpine  
    container_name: nutritionApplicationDb
    environment:
      - POSTGRES_DB=nutritionApplicationDb
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"
    volumes:
      - products-db-data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql


volumes:
  products-db-data:
